### PR TITLE
material-easyCam-1

### PR DESCRIPTION
**Pull request by webmaeistro**
-added easyCam 
-removed orbitControl 
  = smoother user experience when spinning 

-small alterations in html file: moved scripts to header and sketch.js script to body tag. added doc type

-added a canvas element to the css file.

-added a custom version of the easyCam library + createEasyCam()

-experiemnted with ambient, point and directional lights + spectacularMaterial()

props for this

### CODE REVIEW

**Comment by webmaeistro** [comment]
https://p5-perlin-stacked-webmaeistro-branch.netlify.app/ --- branch demo (forgot to include url...) ;D

**Comment by nbogie** [comment]
Thanks very much, @webmaeistro, I like the custom look!   (Sorry for the delay, I just saw this PR this evening after tweaking this repo.)

Next time I work on it I'll integrate your suggestions of anti-aliasing, pixel density support (my current machine is old and doesn't support AA), and disabling right-click!

p.s. You might be interested to see I updated the fragment shader to remove the line around the plate edges.

**Review by webmaeistro — COMMENTED** [review]
Trust in the rust. Proceed

**Review by webmaeistro — COMMENTED** [review]
Cart blach

**Comment by webmaeistro** [comment]
Init repo

**Pull request closed without merging**
